#! /bin/bash

#SBATCH -p q_student
#SBATCH -N 1                 
#SBATCH -c 32   # use all 32 cores 
#SBATCH --cpu-freq=High
#SBATCH --time=5:00

NLIST=(100000000)
MLIST=(200000000)
PLIST=(16 32)
NREP=10

NL=${#NLIST[@]}

BINARY="../bin/merge1_tester"

for (( i=0; i<$NL; i++ ));
do
  n=${NLIST[$i]}
  m=${MLIST[$i]}
  for p in "${PLIST[@]}"
  do
    srun ${BINARY} -n $n -m $m -p $p -r $NREP > "times_merge1/output_${CASE}_${n}_${m}_${p}.out"
  done
done

