#! /bin/bash

#SBATCH -p q_student
#SBATCH -N 1                 
#SBATCH -c 32   # use all 32 cores 
#SBATCH --cpu-freq=High
#SBATCH --time=5:00

NLIST=(1000000 10000000 100000000)
MLIST=(2000000 20000000 200000000)
PLIST=(2 4 8 11 16 32)
NREP=10

BINARY="../bin/merge1_tester"

NL=${#NLIST[@]}

for (( i=0; i<$NL; i++ ));
do
  n=${NLIST[$i]}
  m=${MLIST[$i]}
  for p in "${PLIST[@]}"
  do
    srun ${BINARY} -n $n -m $m -p $p -r $NREP > "times_merge1/output_${CASE}_${n}_${m}_${p}.out"
  done
done

BINARY="../bin/merge2_tester"

for (( i=0; i<$NL; i++ ));
do
  n=${NLIST[$i]}
  m=${MLIST[$i]}
  for p in "${PLIST[@]}"
  do
    srun ${BINARY} -n $n -m $m -p $p -r $NREP > "times_merge2/output_${CASE}_${n}_${m}_${p}.out"
  done
done

BINARY="../bin/merge3_tester"

for (( i=0; i<$NL; i++ ));
do
  n=${NLIST[$i]}
  m=${MLIST[$i]}
  for p in "${PLIST[@]}"
  do
    srun ${BINARY} -n $n -m $m -p $p -r $NREP > "times_merge3/output_${CASE}_${n}_${m}_${p}.out"
  done
done

